FROM node:16-slim

WORKDIR /app

# Copy package.json và package-lock.json
COPY package*.json ./

# Cài đặt các phụ thuộc
RUN npm install

# Copy toàn bộ mã nguồn
COPY . .

# Mở cổng 5001 để socket-server lắng nghe
EXPOSE 5001

# Khởi động server khi container được chạy
CMD ["node", "socket-server.js"] 